import baseline from './public-content.json';
export const cmsCollections=['brand','navigation','home','pages','offers','capability_bundles','dol_services','industries','integrations','partner_categories','opportunity_types','home_outcomes','resources','academy_paths','faq','news','case_studies','job_openings','opportunities','marketplace_listings','service_status'] as const;
export const initialContent:any={...baseline,home:{id:'home',search_indexing:false,headline:{en:'One platform.\nYour business,\nconnected.',bn:'এক প্ল্যাটফর্মে\nআপনার ব্যবসার\nসব সংযোগ।'},description:{en:'Bring your website, commerce and everyday operations together. Start with what you have. Build what comes next.',bn:'ওয়েবসাইট, ই-কমার্স ও দৈনন্দিন পরিচালনাকে একসঙ্গে আনুন। আপনার বর্তমান ব্যবস্থা থেকেই শুরু করুন।'}},news:[],case_studies:[],job_openings:[],opportunities:[],marketplace_listings:[],service_status:[]};
export const contentKey=(collection:string,row:any,i=0)=>String(collection==='pages'?row.route:['brand','home','navigation'].includes(collection)?collection:row.id||row.route||collection+'-'+i);
export function seededRows(collection:string){const raw=initialContent[collection];return (Array.isArray(raw)&&collection!=='navigation'?raw:[raw]).filter(Boolean).map((body,i)=>({id:collection+':'+contentKey(collection,body,i),collection,item_key:contentKey(collection,body,i),body,status:'baseline',version:0,live_version:0,published_body:body,updated_at:null}))}
export function mergeContent(rows:any[]){const content=structuredClone(initialContent),maps:Record<string,Map<string,any>>={};for(const c of cmsCollections)if(!['brand','home','navigation'].includes(c))maps[c]=new Map((content[c]||[]).map((v:any,i:number)=>[contentKey(c,v,i),v]));for(const r of rows){if(!cmsCollections.includes(r.collection))continue;const body=r.published_body===null?null:typeof r.published_body==='string'?JSON.parse(r.published_body):r.published_body;if(['brand','home','navigation'].includes(r.collection)){if(body!==null)content[r.collection]=body;continue}if(body===null)maps[r.collection].delete(r.item_key);else maps[r.collection].set(r.item_key,body)}for(const [c,m] of Object.entries(maps))content[c]=Array.from(m.values());return content}
export function newContentItem(collection:string,key:string){
 if(collection==='pages')return {route:key,layout:'editorial',title:{en:'',bn:''},description:{en:'',bn:''},sections:[]};
 if(collection==='faq')return {id:key,question:{en:'',bn:''},answer:{en:'',bn:''}};
 const prefixes:Record<string,string>={offers:'solutions',capability_bundles:'packages',dol_services:'dol/services',industries:'industries',integrations:'integrations',partner_categories:'partners',opportunity_types:'talent',home_outcomes:'transform',resources:'resources',academy_paths:'academy',news:'newsroom',case_studies:'case-studies',job_openings:'careers',opportunities:'talent',marketplace_listings:'marketplace',service_status:'status'};
 const item:any={id:key,title:{en:'',bn:''},description:{en:'',bn:''},body:{en:'',bn:''},route:'/'+(prefixes[collection]||'resources')+'/'+key,source_refs:[]};
 if(collection==='marketplace_listings'){item.rights_terms={en:'',bn:''};item.support_terms={en:'',bn:''};item.cta_route='/app/records/order'}
 if(collection==='service_status'){delete item.route;item.state='unknown';item.checked_at=null;item.evidence_url=''}
 if(collection==='capability_bundles')item.pricing_variables=[];
 if(collection==='integrations'){item.category='proposed';item.state='adapter_required';item.connected=false}
 if(collection==='opportunities'){item.application_status='planned';item.eligibility={en:'',bn:''};item.rights_terms={en:'',bn:''};item.deadline=null;item.cta_route='/talent/apply?programme='+encodeURIComponent(key)}
 return item;
}
