export type Field={key:string;label:string;bn:string;type?:'text'|'textarea'|'number'|'date'|'email'|'url'|'select';options?:string[];required?:boolean};
export type Module={id:string;title:string;bn:string;group:string;description:string;fields:Field[];external?:string};
const field=(key:string,label:string,bn:string,type:Field['type']='text',required=false,options?:string[]):Field=>({key,label,bn,type,required,options});
const owner=field('owner','Responsible person or role','দায়িত্বপ্রাপ্ত ব্যক্তি বা ভূমিকা');
const due=field('due_date','Target date','লক্ষ্য তারিখ','date');
const evidence=field('evidence','Evidence and source references','প্রমাণ ও উৎসের রেফারেন্স','textarea');
// Which development path a project takes. Absent on records saved before this
// field existed; every reader treats a missing value as 'quick_site', so no
// historical project is retroactively routed to DevScope.
const buildType=field('build_type','Delivery path','ডেলিভারি পদ্ধতি','select',false,['quick_site','custom_software']);
const modules:Module[]=[
{id:'source_response',title:'Source field responses',bn:'উৎসের তথ্য ও উত্তর',group:'Staff',description:'Capture scoped responses against original field and requirement IDs.',external:'Responses are unverified draft evidence. They do not change system fields, identity, rights or approvals.',fields:[field('source_set','Source collection','উৎস সংগ্রহ','select',true,['web','profile','baseline','dol','talent','decisions','agents']),field('source_id','Exact source ID','সঠিক উৎস আইডি','text',true),field('scope_ref','Project or scope reference','প্রকল্প বা পরিধির রেফারেন্স','text',true),field('response','Proposed value or response','প্রস্তাবিত মান বা উত্তর','textarea',true),field('unknowns','Unknowns and validation needed','অজানা তথ্য ও যাচাই','textarea'),evidence]},
{id:'assessment',title:'Transformation assessments',bn:'রূপান্তর মূল্যায়ন',group:'Customer',description:'Your goals, existing systems, sources and proposed next steps.',fields:[field('organization','Organization','প্রতিষ্ঠান','text',true),field('outcomes','Desired outcomes','প্রত্যাশিত ফলাফল','textarea',true),field('site_url','Existing website','বর্তমান ওয়েবসাইট','url'),field('sector','Sector','খাত'),field('country','Country','দেশ'),field('languages','Languages','ভাষা'),field('systems','Existing systems','বর্তমান সিস্টেম','textarea'),field('modules','Selected modules','নির্বাচিত মডিউল','textarea'),field('brand','Brand and content requirements','ব্র্যান্ড ও কনটেন্ট','textarea'),field('rights','Source ownership and permitted use','উৎসের মালিকানা ও ব্যবহারের অনুমতি','textarea'),field('budget','Budget expectation and currency','বাজেট ও মুদ্রা'),field('reporting','Reporting and notification preferences','প্রতিবেদন ও নোটিফিকেশন','textarea'),field('unknowns','Questions to resolve','অমীমাংসিত প্রশ্ন','textarea')]},
{id:'project',title:'Projects',bn:'প্রকল্প',group:'Customer',description:'Turn agreed requirements into owned milestones and reviewable outputs.',fields:[buildType,field('scope','Selected scope','নির্বাচিত পরিধি','textarea',true),owner,due,field('milestones','Milestones','মাইলফলক','textarea'),field('acceptance','Acceptance criteria','গ্রহণযোগ্যতার মানদণ্ড','textarea'),evidence]},
{id:'software_project',title:'Custom software projects',bn:'কাস্টম সফটওয়্যার প্রকল্প',group:'Customer',description:'Describe a customized application to be built for you: portals, ERP, CRM, SaaS, e-commerce, dashboards and workflows.',external:'Submitting an approved revision queues an autonomous build. Hosting, domains, third-party accounts and paid provider usage remain your own responsibility and are not activated by this record.',fields:[field('organization','Organization','প্রতিষ্ঠান','text',true),field('business_objective','Business objective / problem to solve','ব্যবসায়িক লক্ষ্য','textarea',true),field('target_users','Who will use it','ব্যবহারকারী কারা','textarea'),field('requirements','Features and modules required','প্রয়োজনীয় ফিচার ও মডিউল','textarea',true),field('pages','Pages or screens (one per line)','পেজ বা স্ক্রিন','textarea'),field('integrations','Required integrations','প্রয়োজনীয় ইন্টিগ্রেশন','textarea'),field('preferred_stack','Preferred technology (optional)','পছন্দের প্রযুক্তি'),field('preferred_database','Preferred database (optional)','পছন্দের ডেটাবেস'),field('template_ref','Design reference from the Template Library','টেমপ্লেট রেফারেন্স'),field('domain','Intended domain','নির্ধারিত ডোমেইন'),field('srs','Requirements document (SRS)','রিকোয়ারমেন্ট ডকুমেন্ট','textarea'),field('acceptance','Acceptance expectations','গ্রহণযোগ্যতার প্রত্যাশা','textarea'),evidence]},
{id:'task',title:'Tasks and evidence',bn:'কাজ ও প্রমাণ',group:'Staff',description:'Track assignments, effort, blockers and evidence independently.',fields:[owner,due,field('project_ref','Project reference','প্রকল্প রেফারেন্স'),field('expected_output','Expected output','প্রত্যাশিত আউটপুট','textarea',true),field('hours','Effort hours','কাজের ঘণ্টা','number'),field('blockers','Blockers and support needed','প্রতিবন্ধকতা ও সহায়তা','textarea'),evidence]},
{id:'preview',title:'Previews and corrections',bn:'প্রিভিউ ও সংশোধন',group:'Customer',description:'Keep preview versions, customer feedback and review evidence together.',fields:[field('project_ref','Project reference','প্রকল্প রেফারেন্স'),field('preview_ref','Preview or artifact reference','প্রিভিউ বা আর্টিফ্যাক্ট'),field('corrections','Requested corrections','চাওয়া সংশোধন','textarea',true),evidence]},
{id:'quote',title:'Offers and quotes',bn:'অফার ও কোটেশন',group:'Finance',description:'Prepare scope and commercial terms for independent price approval.',external:'Pricebook and commercial approval are not configured. Records are unissued drafts.',fields:[field('package','Package or offer','প্যাকেজ বা অফার'),field('scope','Included scope','অন্তর্ভুক্ত পরিধি','textarea',true),field('setup','Proposed setup amount','প্রস্তাবিত সেটআপ মূল্য','number'),field('recurring','Proposed recurring amount','প্রস্তাবিত পুনরাবৃত্ত মূল্য','number'),field('currency','Currency','মুদ্রা'),field('usage','Usage limits and overages','ব্যবহারের সীমা','textarea'),field('terms','Terms, tax and exclusions','শর্ত, কর ও বর্জন','textarea'),evidence]},
{id:'invoice',title:'Billing and reconciliation',bn:'বিলিং ও সমন্বয়',group:'Finance',description:'Keep external invoice and settlement references distinct.',external:'No payment provider is connected; invoice records do not confirm payment.',fields:[field('provider_ref','Invoice/provider reference','ইনভয়েস বা প্রদানকারীর রেফারেন্স'),field('amount','Recorded amount','রেকর্ডকৃত পরিমাণ','number'),field('currency','Currency','মুদ্রা'),field('payment_state','Observed payment state','পর্যবেক্ষিত অর্থপ্রদানের অবস্থা','select',false,['unknown','unpaid','pending_verification','disputed']),evidence]},
{id:'subscription',title:'Subscriptions and usage',bn:'সাবস্ক্রিপশন ও ব্যবহার',group:'Customer',description:'Record requested entitlements, renewal dates and usage evidence.',external:'Billing activation and entitlements require a connected provider and approval.',fields:[field('package','Requested package','প্রয়োজনীয় প্যাকেজ'),field('limits','Entitlement and usage limits','সুবিধা ও ব্যবহারের সীমা','textarea'),field('renewal','Renewal date','নবায়নের তারিখ','date'),evidence]},
{id:'product',title:'Products and inventory',bn:'পণ্য ও মজুত',group:'Merchant',description:'Prepare products and inventory source mappings.',external:'Stock and catalogue synchronization require an approved source connector.',fields:[field('sku','SKU','এসকেইউ','text',true),field('description','Product description','পণ্যের বিবরণ','textarea'),field('quantity','Reported quantity','প্রতিবেদিত পরিমাণ','number'),field('price','Proposed price','প্রস্তাবিত মূল্য','number'),field('currency','Currency','মুদ্রা'),field('source','Inventory source','মজুতের উৎস'),evidence]},
{id:'order',title:'Orders and delivery',bn:'অর্ডার ও সরবরাহ',group:'Merchant',description:'Track order requests, fulfillment evidence and exceptions.',external:'These records do not place an order or confirm stock, payment or delivery.',fields:[field('order_ref','Order reference','অর্ডার রেফারেন্স'),field('items','Items and quantities','পণ্য ও পরিমাণ','textarea',true),field('fulfillment','Fulfillment requirements','সরবরাহের শর্ত','textarea'),field('delivery_ref','Delivery provider reference','সরবরাহকারী রেফারেন্স'),evidence]},
{id:'return',title:'Returns and disputes',bn:'রিটার্ন ও বিরোধ',group:'Merchant',description:'Document return, refund and dispute requests for review.',external:'No refund or financial adjustment is executed here.',fields:[field('order_ref','Order reference','অর্ডার রেফারেন্স','text',true),field('reason','Reason','কারণ','textarea',true),field('requested_remedy','Requested resolution','প্রত্যাশিত সমাধান','textarea'),evidence]},
{id:'ticket',title:'Support tickets',bn:'সাপোর্ট টিকিট',group:'Customer',description:'Capture issues, impact, evidence and follow-up.',fields:[field('category','Category','বিভাগ','select',true,['technical','billing','access','service','other']),field('severity','Impact','প্রভাব','select',true,['low','normal','high','critical']),field('description','What happened?','কী ঘটেছে?','textarea',true),field('expected','Expected result','প্রত্যাশিত ফলাফল','textarea'),evidence]},
{id:'feedback',title:'Feedback and appeals',bn:'মতামত ও আপিল',group:'Customer',description:'Separate complaints, suggestions, feature requests and appeals.',fields:[field('category','Feedback type','মতামতের ধরন','select',true,['feedback','complaint','suggestion','feature_request','appeal','confidential_report']),field('description','Details','বিস্তারিত','textarea',true),field('requested_outcome','Requested outcome','প্রত্যাশিত ফলাফল','textarea'),evidence]},
{id:'partner',title:'Partner applications',bn:'অংশীদার আবেদন',group:'Partner',description:'Review provider, reseller, delivery, research and referral applications.',fields:[field('organization','Organization','প্রতিষ্ঠান','text',true),field('category','Partner category','অংশীদারের ধরন','select',true,['technology','delivery','reseller','white_label','referral','industry','education','research']),field('capability','Capabilities and references','দক্ষতা ও রেফারেন্স','textarea',true),field('rights','Rights and territory','অধিকার ও অঞ্চল','textarea'),field('support','Support commitments','সাপোর্টের অঙ্গীকার','textarea'),evidence]},
{id:'listing',title:'Marketplace listings',bn:'মার্কেটপ্লেস তালিকা',group:'Partner',description:'Prepare versioned listings, licence terms and compatibility evidence.',external:'Listing approval, commercial rights and activation are separate decisions.',fields:[field('category','Category','বিভাগ'),field('version','Version','সংস্করণ'),field('compatibility','Compatibility','সামঞ্জস্য','textarea'),field('license','Licence and rights','লাইসেন্স ও অধিকার','textarea'),field('support','Support owner and terms','সাপোর্টের দায়িত্ব ও শর্ত','textarea'),evidence]},
{id:'commission',title:'Partner rewards',bn:'অংশীদার পুরস্কার',group:'Partner',description:'Track reward claims against eligible verified outcomes.',external:'No commission calculation or payout is certified or executed.',fields:[field('partner_ref','Partner reference','অংশীদার রেফারেন্স'),field('sale_ref','Verified sale reference','বিক্রয়ের রেফারেন্স'),field('rules','Applicable rule version','প্রযোজ্য নিয়মের সংস্করণ'),evidence]},
{id:'field_visit',title:'Field work and installation',bn:'মাঠকাজ ও ইনস্টলেশন',group:'Staff',description:'Plan visits and installations with consent, evidence and handover.',external:'Location tracking, dispatch, ISP provisioning and SLA timers are not connected.',fields:[owner,due,field('service_ref','Service/order reference','সেবা বা অর্ডার রেফারেন্স'),field('location','Agreed service location','সম্মত সেবাস্থল'),field('purpose','Visit purpose and consent','ভ্রমণের উদ্দেশ্য ও সম্মতি','textarea'),field('materials','Materials and expenses','উপকরণ ও ব্যয়','textarea'),evidence]},
{id:'opportunity',title:'Business opportunities',bn:'ব্যবসার সুযোগ',group:'Executive',description:'Turn customer problems and market evidence into testable opportunities.',fields:[field('problem','Customer problem','গ্রাহকের সমস্যা','textarea',true),field('beneficiary','Beneficiary','সুবিধাভোগী'),field('hypothesis','Value hypothesis','সম্ভাব্য মূল্য','textarea'),field('sources','Sources and dates','উৎস ও তারিখ','textarea'),owner,due]},
{id:'challenge',title:'Competitions and challenges',bn:'প্রতিযোগিতা ও চ্যালেঞ্জ',group:'Academy',description:'Prepare eligibility, judging, prize and appeal rules before opening entries.',external:'No competition or prize programme is open until its charter and funding are approved.',fields:[field('problem','Challenge problem','চ্যালেঞ্জের সমস্যা','textarea',true),field('eligibility','Eligibility and participation terms','যোগ্যতা ও অংশগ্রহণের শর্ত','textarea'),field('rubric','Judging criteria','মূল্যায়নের মানদণ্ড','textarea'),field('prizes','Funding and prize terms','তহবিল ও পুরস্কারের শর্ত','textarea'),field('appeals','Conflict and appeal process','স্বার্থের সংঘাত ও আপিল','textarea'),due]},
{id:'application',title:'Talent and student applications',bn:'প্রতিভা ও শিক্ষার্থী আবেদন',group:'Academy',description:'Capture voluntary participation, skills evidence and supervision needs.',fields:[field('programme','Programme or challenge reference','কর্মসূচি বা চ্যালেঞ্জ রেফারেন্স'),field('participation','Participation type','অংশগ্রহণের ধরন','select',true,['student_project','capstone','internship','independent_talent','alumni','mentor','industry']),field('skills','Skills and evidence','দক্ষতা ও প্রমাণ','textarea',true),field('availability','Availability and language','সময় ও ভাষা'),field('supervision','Supervision and learning goals','তত্ত্বাবধান ও শিক্ষার লক্ষ্য','textarea'),field('consent','Participation and publicity preferences','অংশগ্রহণ ও প্রচারের পছন্দ','textarea')]},
{id:'research',title:'Research and commercialization',bn:'গবেষণা ও বাণিজ্যিকীকরণ',group:'Academy',description:'Connect real problems, research evidence, rights and commercial pathways.',fields:[field('problem','Research problem','গবেষণার সমস্যা','textarea',true),field('investigators','Investigators and contributors','গবেষক ও অবদানকারী'),field('method','Method and reproducibility','পদ্ধতি ও পুনরুৎপাদনযোগ্যতা','textarea'),field('ethics','Ethics and data permissions','নৈতিকতা ও তথ্যের অনুমতি','textarea'),field('ip','Background IP and ownership','পূর্ববর্তী মেধাস্বত্ব ও মালিকানা','textarea'),field('route','Commercialization route','বাণিজ্যিকীকরণের পথ','select',false,['research_only','licensing','customer_pilot','managed_service','reusable_module','spin_out','social_impact']),evidence]},
{id:'judging',title:'Judging and review',bn:'বিচার ও পর্যালোচনা',group:'Academy',description:'Record rubric evidence, declared conflicts and review notes.',external:'This workspace does not select winners, issue grades or approve awards.',fields:[field('challenge_ref','Challenge reference','চ্যালেঞ্জ রেফারেন্স'),field('submission_ref','Submission reference','জমার রেফারেন্স'),field('conflict','Conflict declaration','স্বার্থের সংঘাতের ঘোষণা','textarea',true),field('rubric','Rubric version and criterion evidence','রুব্রিক সংস্করণ ও প্রমাণ','textarea',true),evidence]},
{id:'booking',title:'Resource requests',bn:'সম্পদ ব্যবহারের অনুরোধ',group:'Academy',description:'Request labs, mentors, GPU, hosting and other resources.',external:'Requests do not reserve capacity. Provider rights, quotas and expiring holds require integration.',fields:[field('resource','Resource and provider','সম্পদ ও প্রদানকারী','text',true),field('location','Location or remote access','অবস্থান বা দূরবর্তী ব্যবহার'),field('start','Requested start','শুরুর তারিখ','date'),field('end','Requested end','শেষের তারিখ','date'),field('capacity','Capacity and dimensions','ধারণক্ষমতা ও পরিমাপ','textarea'),field('purpose','Purpose and permissions','উদ্দেশ্য ও অনুমতি','textarea',true)]},
{id:'learning',title:'Academy and Living Labs',bn:'একাডেমি ও লিভিং ল্যাব',group:'Academy',description:'Plan learning paths and supervised practical work.',fields:[field('path','Learning path','শিক্ষার পথ'),field('goals','Learning outcomes','শিক্ষার ফলাফল','textarea',true),field('supervisor','Supervisor','তত্ত্বাবধায়ক'),field('assessment','Assessment evidence','মূল্যায়নের প্রমাণ','textarea'),due]},
{id:'market_review',title:'Market and technology intelligence',bn:'বাজার ও প্রযুক্তি বিশ্লেষণ',group:'Executive',description:'Compare sourced alternatives and prepare bounded experiments.',external:'Monthly research and new tool installation are not automated.',fields:[field('question','Comparison question','তুলনার প্রশ্ন','textarea',true),field('market','Market and time window','বাজার ও সময়কাল'),field('sources','Sources and observation dates','উৎস ও পর্যবেক্ষণের তারিখ','textarea',true),field('comparison','Comparable scope, prices and uncertainty','তুলনীয় পরিধি, মূল্য ও অনিশ্চয়তা','textarea'),field('experiment','Proposed experiment and stop rule','প্রস্তাবিত পরীক্ষা ও বন্ধের নিয়ম','textarea'),owner]},
{id:'country',title:'Country and language readiness',bn:'দেশ ও ভাষার প্রস্তুতি',group:'Tenant admin',description:'Plan country, seller, language, payment and support requirements.',fields:[field('country','Country','দেশ','text',true),field('locales','Locales and translation status','ভাষা ও অনুবাদের অবস্থা'),field('seller','Legal seller and rights','আইনগত বিক্রেতা ও অধিকার'),field('payment','Payment, currency, tax and refunds','পেমেন্ট, মুদ্রা, কর ও ফেরত','textarea'),field('data','Data location and transfers','তথ্যের অবস্থান ও স্থানান্তর','textarea'),field('support','Support language and hours','সাপোর্টের ভাষা ও সময়','textarea'),evidence]},
{id:'integration',title:'Integration requests',bn:'ইন্টিগ্রেশন অনুরোধ',group:'Tenant admin',description:'Review API and MCP adapters, source ownership and testing.',external:'No connector is activated by saving this record. Do not enter tokens or passwords.',fields:[field('provider','Provider/system','প্রদানকারী বা সিস্টেম','text',true),field('purpose','Purpose and allowed data','উদ্দেশ্য ও অনুমোদিত তথ্য','textarea',true),field('owner','Source-system owner','মূল সিস্টেমের দায়িত্বপ্রাপ্ত'),field('schema','Contract/schema version reference','চুক্তি বা স্কিমা সংস্করণ'),field('scope','Requested permissions','প্রয়োজনীয় অনুমতি','textarea'),evidence]},
{id:'agent',title:'AI and agent registry',bn:'এআই ও এজেন্ট তালিকা',group:'Platform admin',description:'Define bounded agent missions, data, tools and evaluation.',external:'Agent execution is disabled until approved provider, tool and authority bindings are configured.',fields:[field('mission','Mission','লক্ষ্য','textarea',true),field('audience','Audience','ব্যবহারকারী'),field('tools','Allowed tools and data','অনুমোদিত টুল ও তথ্য','textarea'),field('limits','Budget, step and time limits','বাজেট, ধাপ ও সময়সীমা','textarea'),field('approvals','Approval and escalation rules','অনুমোদন ও এসকেলেশন','textarea'),field('evaluation','Evaluation and stop conditions','মূল্যায়ন ও বন্ধের শর্ত','textarea'),owner]},
{id:'content',title:'Content and page studio',bn:'কনটেন্ট ও পেজ স্টুডিও',group:'Tenant admin',description:'Draft pages, menus, articles, offers, jobs and multilingual content.',external:'Content remains private until editorial rights, translation and release review are completed.',fields:[field('content_type','Content type','কনটেন্টের ধরন','select',true,['page','navigation','article','news','offer','course','job','knowledge','image_rights','case_study','faq']),field('route','Intended route','নির্ধারিত রুট'),field('locale','Locale','ভাষা','select',true,['en','bn']),field('body','Content','কনটেন্ট','textarea',true),field('sources','Source and rights evidence','উৎস ও অধিকারের প্রমাণ','textarea'),field('seo','SEO title, description and canonical intent','এসইও শিরোনাম, বিবরণ ও ক্যানোনিক্যাল','textarea')]},
{id:'configuration',title:'Forms, workflows and settings',bn:'ফর্ম, কর্মপ্রবাহ ও সেটিংস',group:'Tenant admin',description:'Prepare versioned field, workflow, permission and notification changes.',external:'Configuration drafts do not change schemas, permissions or production behavior.',fields:[field('type','Configuration type','কনফিগারেশনের ধরন','select',true,['form','field','workflow','report','notification','role','branding','policy','translation','navigation']),field('target','Target and current version','লক্ষ্য ও বর্তমান সংস্করণ','text',true),field('proposed','Proposed change','প্রস্তাবিত পরিবর্তন','textarea',true),field('impact','Dependencies, migration and permission impact','নির্ভরতা, স্থানান্তর ও অনুমতির প্রভাব','textarea'),field('rollback','Rollback plan','পূর্বাবস্থায় ফেরার পরিকল্পনা','textarea'),evidence]},
{id:'campaign',title:'Newsletters and campaigns',bn:'নিউজলেটার ও ক্যাম্পেইন',group:'Partner',description:'Prepare consented campaigns and channel content for review.',external:'Nothing is sent, posted or advertised from this workspace.',fields:[field('channel','Channel','মাধ্যম','select',true,['email','whatsapp','facebook','instagram','youtube','linkedin','search','other']),field('purpose','Audience and purpose','ব্যবহারকারী ও উদ্দেশ্য','textarea'),field('content','Draft content','খসড়া কনটেন্ট','textarea',true),field('consent','Consent and suppression references','সম্মতি ও বাদ দেওয়ার রেফারেন্স','textarea'),field('budget','Budget and currency','বাজেট ও মুদ্রা'),evidence]},
{id:'decision',title:'Decisions and release review',bn:'সিদ্ধান্ত ও রিলিজ পর্যালোচনা',group:'Executive',description:'Prepare scoped decisions with independent authority and evidence.',external:'Saving or reviewing a record is not formal approval, contract freeze or production release.',fields:[field('scope','Scope and artifact version','পরিধি ও আর্টিফ্যাক্ট সংস্করণ','textarea',true),field('decision_type','Decision type','সিদ্ধান্তের ধরন','select',true,['source_reconciliation','design_adoption','contract_freeze','staging_entry','production_release']),field('conditions','Conditions and dependencies','শর্ত ও নির্ভরতা','textarea'),field('authority','Required approving authority','প্রয়োজনীয় অনুমোদনকারী'),evidence,field('rollback','Recovery/rollback evidence','পুনরুদ্ধার বা রোলব্যাকের প্রমাণ','textarea')]},
{id:'incident',title:'Incidents and recovery',bn:'ঘটনা ও পুনরুদ্ধার',group:'Platform admin',description:'Record service incidents, corrections and recovery evidence.',external:'The website owner can publish reviewed status updates from Website content. Automated provider monitoring is not connected.',fields:[field('impact','Impact and affected service','প্রভাব ও সংশ্লিষ্ট সেবা','textarea',true),owner,field('timeline','Incident timeline','ঘটনার সময়রেখা','textarea'),field('recovery','Recovery and reconciliation','পুনরুদ্ধার ও সমন্বয়','textarea'),evidence]}
];
export default modules;
export const moduleById=(id:string)=>modules.find(m=>m.id===id);
