import templates from './templates.json';
import {SITE_TEMPLATES,findTemplate,applyStyle,renderMarketingHtml,renderPreviewDocument,renderStaticSite,type TemplateStyle} from './site-templates';
export type Project={id:string;name:string;category:string;design:string;templateId?:string;templateName?:string;templateLayout?:string;templateStyle?:TemplateStyle;stack:string;database:string;domain:string;pages:string[];brief:string;srs:string;aiPageBodies?:Record<string,string>;video:string;social:Record<string,string>;integrations:string[];mobile:string;approved:boolean;approvedAt?:string;revision:number};
export {SITE_TEMPLATES,findTemplate,applyStyle,renderMarketingHtml,renderPreviewDocument} from './site-templates';
export type {TemplateStyle} from './site-templates';
export const adapters=[{id:'react',name:'React + FastAPI',db:'PostgreSQL',ready:true},{id:'nextjs',name:'Next.js + FastAPI',db:'PostgreSQL',ready:true},{id:'wordpress',name:'WordPress',db:'MariaDB',ready:true},{id:'laravel',name:'Laravel',db:'MySQL',ready:true},{id:'angular',name:'Angular',db:'PostgreSQL',ready:true},{id:'odoo18',name:'Odoo 18',db:'PostgreSQL',ready:true},{id:'odoo19',name:'Odoo 19',db:'PostgreSQL',ready:true},{id:'html',name:'Static HTML',db:'None',ready:true},{id:'nuxt',name:'Nuxt.js',db:'PostgreSQL',ready:false},{id:'joomla',name:'Joomla',db:'MySQL',ready:false}];
export function validate(p:Project){const errors:string[]=[];if(!p.name.trim())errors.push('Enter a project name.');if(!p.category||!SITE_TEMPLATES.some(t=>t.id===p.design))errors.push('Choose a category and template.');const a=adapters.find(a=>a.id===p.stack);if(!a?.ready)errors.push('Choose an available stack adapter.');if(a?.db!==p.database)errors.push('Select the compatible database.');if(!/^(?=.{1,253}$)(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,63}$/.test(p.domain))errors.push('Enter a domain without https:// or a path.');if(!p.pages.length||p.pages.length>30||p.pages.some(x=>!x.trim()||x.length>80))errors.push('Add 1–30 page names, each up to 80 characters.');for(const u of [p.video,...Object.values(p.social)])if(u){try{if(!['https:','http:'].includes(new URL(u).protocol))throw Error()}catch{errors.push('Use complete https:// links for video and social profiles.');break;}}return errors;}
export function srs(p:Project){return `# ${p.name} — Requirements\n\nProject: ${p.id}\nCategory: ${p.category}\nTemplate profile: ${p.templateName||'Not selected'} (${p.templateId||'none'})\nLayout: ${p.templateLayout||'Not selected'} · Visual direction: ${p.templateStyle||'Not selected'}\nDesign: ${p.design}\nStack: ${p.stack}\nDatabase: ${p.database}\nDomain: ${p.domain} (ownership / DNS / TLS not yet verified)\n\n## Business objective\n${p.brief||'To be confirmed by the project owner.'}\n\n## Pages\n${p.pages.map((x,i)=>`REQ-PAGE-${String(i+1).padStart(3,'0')}: ${x}${p.stack==='html'?'; static HTML file, edited directly':'; editable in the CMS'}.`).join('\n')}\n\n## Runtime requirements\n${p.stack==='html'?'Static HTML files with no database, backend or CMS; content is edited directly in the .html files; responsive frontend; source export.':`Database-backed pages; authenticated CMS; ${p.stack==='wordpress'?'native WordPress editing':'contact enquiry storage'}; responsive frontend; source export; institution-controlled deployment.`}\n\n## Requested optional integrations\n${p.integrations.join(', ')||'None selected'} — unconfigured until credentials, purpose and acceptance tests are supplied.\n\n## Template scope\nThe selected template profile applies a real page blueprint and rendered visual direction from the Template Library (see live preview). It is a configurable starter, not a claim that a finished public website, licensed third-party design or live integration already exists.\n\n## Mobile recommendation\n${p.mobile||'PWA-first is suitable for repeat visits; native features require a separate scoped build.'}\n\n## Release gates\nReview content rights, run local QA, verify CMS access, restore a backup, connect domain and TLS, obtain project-owner launch acceptance. No payment, messaging or remote deployment is authorised by this document.\n\n## Additional requirements\n${p.srs||'None provided.'}\n`;}
function sqlLiteral(s:string){return "'"+String(s).replace(/'/g,"''")+"'"}
const xmlEscape=(s:string)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'} as any)[c]);
// Matches uploaded/typed SRS text against page names: a line that (after stripping
// markdown heading marks, list markers and a trailing colon) equals a page title
// starts that page's section; everything until the next matching heading belongs to it.
function srsSections(srsText:string,titles:string[]):Record<string,string>{
 const result:Record<string,string>={};
 if(!srsText||!srsText.trim())return result;
 const norm=(s:string)=>s.trim().toLowerCase().replace(/^#{1,6}\s*/,'').replace(/^[-*•]\s*/,'').replace(/^\d+[.)]\s*/,'').replace(/[:\-–]\s*$/,'').trim();
 const titleByKey=new Map(titles.map(t=>[norm(t),t]));
 let current:string|null=null,buf:string[]=[];
 const flush=()=>{if(current&&buf.join('\n').trim())result[current]=buf.join('\n').trim();buf=[]};
 for(const line of srsText.replace(/\r\n/g,'\n').split('\n')){
  const key=line.trim().length<100?titleByKey.get(norm(line)):undefined;
  if(key){flush();current=key}
  else if(current)buf.push(line);
 }
 flush();
 return result;
}
export function filesFor(p:Project){const errors=validate(p);if(errors.length)throw Error(errors.join(' '));if(!p.approved)throw Error('Approve the current SRS before generation.');const t=templates as Record<string,Record<string,string>>;const files:Record<string,string>={...(['wordpress','laravel','odoo18','odoo19','html'].includes(p.stack)?{}:t.shared),...t[p.stack]};const seen=new Set<string>();const template=applyStyle(findTemplate(p.design),p.templateStyle||'ocean');const srsMap=srsSections(p.srs,p.pages);const pages=p.pages.map((title,i)=>{let slug=title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'page-'+(i+1);if(i===0)slug='home';if(seen.has(slug))slug+='-'+(i+1);seen.add(slug);return {slug,title,body:p.aiPageBodies?.[title]||srsMap[title]||(p.stack==='html'?`${p.name}\n\n${p.brief||'Add approved content directly in this page.'}\n\n${title} content: edit this .html file before launch.`:`${p.name}\n\n${p.brief||'Add approved content in the CMS.'}\n\n${title} content: edit this draft in your CMS before launch.`)}});const {html:heroHtml,css:heroCss}=renderMarketingHtml(template,{name:p.name,category:p.category,brief:p.brief});const config:any={name:p.name,category:p.category,design:p.design,template:template.id,templateName:template.name,templateProfile:{id:p.templateId||null,name:p.templateName||null,layout:p.templateLayout||null,style:p.templateStyle||null},domain:p.domain,video:p.video,social:p.social,pages,heroHtml,heroCss};for(const k of Object.keys(files))files[k]=files[k].replace('__CONFIG__',JSON.stringify(config).replace(/</g,'\\u003c')).replace('__PROJECT_NAME__',p.name||'Website');files['seed.json']=JSON.stringify({...config,hero_html:heroHtml,hero_css:heroCss},null,2);files['project.json']=JSON.stringify(p,null,2);files['REQUIREMENTS.md']=srs(p);files['release-status.json']=JSON.stringify({generated_at:new Date().toISOString(),generator:'DUDOS-builder/1.1.0',template_profile:{id:p.templateId||null,name:p.templateName||null,layout:p.templateLayout||null,style:p.templateStyle||null},srs_approved_at:p.approvedAt,code_generated:true,database_provisioned:false,browser_qa:'pending local execution',dns:'unverified',deployed:false,integrations:'not configured'},null,2);
if(p.stack==='wordpress'){files['database/README.md']=`# Database — ${p.name}\n\nWordPress stores content in its own MariaDB schema (~12 core tables), created automatically on first boot — there is no separate SQL file to restore by hand.\n\nThe page content you previewed in the builder is captured in ./seed.json (also included at the project root) and is applied automatically the first time you run the install script, via bootstrap.sh + import.php (WP-CLI). To re-apply it to a fresh database, rerun \`docker compose --profile setup run --rm cli\` after the \`db\`/\`wordpress\` services are healthy.\n\nTo back up an installed site's real database later, use \`docker compose exec db mariadb-dump -u wordpress -p wordpress > backup.sql\`.\n`;files['database/content-export.json']=JSON.stringify({name:config.name,template:config.template,pages:config.pages},null,2);}
else if(p.stack==='laravel'){files['database/README.md']=`# Database — ${p.name}\n\nLaravel manages its own MySQL schema through the migrations shipped in backend/database/migrations — there is no separate SQL file to restore by hand.\n\nThe page content you previewed in the builder is captured in ./seed.json (also included at the project root) and is applied automatically on first boot by backend/database/seeders/DatabaseSeeder.php, run from ops/entrypoint.sh. The seeder is idempotent; rerunning it never duplicates rows.\n\nTo back up an installed site's real database later, use \`bash ops/backup.sh\`.\n`;files['database/content-export.json']=JSON.stringify({name:config.name,template:config.template,pages:config.pages},null,2);}
else if(p.stack==='odoo18'||p.stack==='odoo19'){const slugKey=(s:string)=>s.replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'')||'page';const pageXml=pages.map(pg=>{const id='dudos_page_'+slugKey(pg.slug);const url=pg.slug==='home'?'/':'/'+pg.slug;const body=pg.slug==='home'?`<style>${heroCss}</style>\n${heroHtml}`:`<section class="container py-5"><p class="text-uppercase text-muted small mb-1">${xmlEscape(p.category)}</p><h1>${xmlEscape(pg.title)}</h1><p style="white-space:pre-wrap">${xmlEscape(pg.body)}</p></section>`;return `<template id="${id}" name="${xmlEscape(pg.title)}"><t t-call="website.layout"><div id="wrap" class="oe_structure">${body}</div></t></template>\n<record id="${id}_page" model="website.page"><field name="url">${url}</field><field name="name">${xmlEscape(pg.title)}</field><field name="type">qweb</field><field name="view_id" ref="${id}"/><field name="is_published">False</field><field name="website_indexed">True</field></record>`}).join('\n');files['odoo_module/data/pages.xml']=`<?xml version="1.0" encoding="utf-8"?>\n<odoo><data noupdate="1">\n${pageXml}\n</data></odoo>\n`;const menuXml=pages.map((pg,i)=>{const id='dudos_menu_'+slugKey(pg.slug);const url=pg.slug==='home'?'/':'/'+pg.slug;return `<record id="${id}" model="website.menu"><field name="name">${xmlEscape(pg.title)}</field><field name="url">${url}</field><field name="parent_id" ref="website.main_menu"/><field name="sequence">${(i+1)*10}</field></record>`}).join('\n');files['odoo_module/data/menu.xml']=`<?xml version="1.0" encoding="utf-8"?>\n<odoo><data noupdate="1">\n${menuXml}\n</data></odoo>\n`;files['database/README.md']=`# Target database — ${p.name}\n\nThis module installs into your existing Odoo ${p.stack==='odoo18'?'18':'19'} database. No new database is created, migrated or provisioned by this download — see odoo_module/README.md for installing the module into your Odoo addons path.\n`;}
else if(p.stack==='html'){Object.assign(files,renderStaticSite(template,{name:p.name,category:p.category,brief:p.brief,domain:p.domain,video:p.video,social:p.social},pages));files['README.md']=`# ${p.name} — static export\n\nPlain HTML, CSS and no JavaScript framework — no server, database, build step or install script required. Open index.html directly, or upload every file in this folder as-is to any static host (Netlify, GitHub Pages, S3, Cloudflare Pages, or a plain web server via FTP).\n\nEdit the .html files directly for content changes, or come back to the Website Builder and regenerate. See database/README.md about the contact page.\n`;files['database/README.md']=`# No database — ${p.name}\n\nThis is a static HTML export. There is no database, backend or CMS; page content lives directly in the .html files. See README.md for hosting instructions and the contact page's note about adding a form.\n`;}
else{const schema=t.shared['backend/migrations/001_initial.sql']||'';files['database/schema.sql']=schema;const now=new Date().toISOString();const rows=pages.map(pg=>{const data=JSON.stringify({slug:pg.slug,title:pg.title,body:pg.body,revision:1});return `INSERT INTO records (id, owner, kind, data, revision, updated) VALUES ('page:${pg.slug}', 'admin', 'page', ${sqlLiteral(data)}, 1, ${sqlLiteral(now)}) ON CONFLICT (id) DO NOTHING;`}).join('\n');files['database/seed.sql']=`-- Seeds the pages shown in the builder preview for ${p.name}.\n-- Apply after schema.sql (the install script already runs both automatically on first boot).\n${rows}\n`;files['database/README.md']=`# Database — ${p.name}\n\nPostgreSQL schema: ./schema.sql (same as backend/migrations/001_initial.sql).\nSeed data matching the previewed content: ./seed.sql.\n\nThe install script applies both automatically on first boot via the API container's migration step. To restore into a running stack manually:\n\n\`\`\`\ndocker compose exec -T db psql -U dudos -d dudos -f - < database/schema.sql\ndocker compose exec -T db psql -U dudos -d dudos -f - < database/seed.sql\n\`\`\`\n`;files['frontend/public/robots.txt']=`User-agent: *\nDisallow:\nSitemap: https://${p.domain}/sitemap.xml\n`;files['frontend/public/sitemap.xml']=`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://${p.domain}/</loc></url></urlset>`;}
files['preview.html']=renderPreviewDocument(template,{name:p.name,category:p.category,brief:p.brief});
return files;}
// ZIP store format: no executable bundler or external service required.
export function zip(files:Record<string,string>){const enc=new TextEncoder();let offset=0;const local:Uint8Array[]=[];const central:Uint8Array[]=[];const crc=(data:Uint8Array)=>{let c=0xffffffff;for(const x of data){c^=x;for(let i=0;i<8;i++)c=c&1?(c>>>1)^0xedb88320:c>>>1;}return(c^0xffffffff)>>>0;};const header=(length:number)=>{const b=new Uint8Array(length);return{b,v:new DataView(b.buffer)}};for(const [name,content]of Object.entries(files)){const n=enc.encode(name),d=enc.encode(content),c=crc(d),h=header(30+n.length);h.v.setUint32(0,0x04034b50,true);h.v.setUint16(4,20,true);h.v.setUint16(6,0x800,true);h.v.setUint32(14,c,true);h.v.setUint32(18,d.length,true);h.v.setUint32(22,d.length,true);h.v.setUint16(26,n.length,true);h.b.set(n,30);local.push(h.b,d);const z=header(46+n.length);z.v.setUint32(0,0x02014b50,true);z.v.setUint16(4,20,true);z.v.setUint16(6,20,true);z.v.setUint16(8,0x800,true);z.v.setUint32(16,c,true);z.v.setUint32(20,d.length,true);z.v.setUint32(24,d.length,true);z.v.setUint16(28,n.length,true);z.v.setUint32(42,offset,true);z.b.set(n,46);central.push(z.b);offset+=h.b.length+d.length;}const size=central.reduce((s,x)=>s+x.length,0),end=header(22);end.v.setUint32(0,0x06054b50,true);end.v.setUint16(8,central.length,true);end.v.setUint16(10,central.length,true);end.v.setUint32(12,size,true);end.v.setUint32(16,offset,true);return new Blob([...local,...central,end.b] as BlobPart[],{type:'application/zip'});}
export function download(name:string,data:Blob|string){const url=URL.createObjectURL(typeof data==='string'?new Blob([data],{type:'text/plain;charset=utf-8'}):data);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
