import {SITE_TEMPLATES,type TemplateStyle,type SiteTemplate} from './site-templates';
export type {TemplateStyle};
export type TemplateProfile={id:string;name:string;industry:string;category:string;layout:string;layoutLabel:string;siteTemplateId:string;siteTemplateName:string;heroShape:SiteTemplate['heroShape'];style:TemplateStyle;styleLabel:string;summary:string;pages:string[];capabilities:string[];supportedStacks:string[]};
const industries=[['Business services','Business services',['Home','About','Services','Case studies','Contact']],['Education','Education',['Home','Programmes','Admissions','Faculty','Contact']],['E-commerce','E-commerce',['Home','Shop','Categories','Offers','Contact']],['Restaurant','Restaurant',['Home','Menu','Our story','Reservations','Contact']],['Laundry','Laundry',['Home','Laundry services','Pricing','Collection & delivery','Contact']],['Healthcare','Business services',['Home','Services','Doctors','Appointments','Contact']],['Real estate','Business services',['Home','Properties','Services','Insights','Contact']],['Travel & tourism','Business services',['Home','Experiences','Packages','Gallery','Contact']],['Hospitality','Business services',['Home','Rooms','Dining','Experiences','Contact']],['NGO & social impact','Business services',['Home','Our work','Programmes','Impact','Contact']],['Professional portfolio','Portfolio',['Home','About','Work','Services','Contact']],['Technology & SaaS','Business services',['Home','Product','Solutions','Resources','Contact']],['Manufacturing','Business services',['Home','Products','Capabilities','Quality','Contact']],['Events & community','Business services',['Home','Events','Community','Partners','Contact']],['Research & innovation','Education',['Home','Research','Projects','Publications','Contact']]] as const;
// Each layout maps to one of the eight real, hand-built hero layouts in site-templates.ts —
// a profile's "layout" is a genuine structural difference, not a label.
const layouts=[['service-led','Service-led','A focused services page with a clear enquiry path.','harbor'],['catalogue','Catalogue','A browse-first layout for products, offers and categories.','fresh-press'],['story-led','Story-led','A mission and credibility layout for institutional narratives.','brightline-academy'],['conversion','Conversion-led','A campaign-style layout with one primary call to action.','ember-kitchen'],['portfolio','Portfolio-led','A work and proof layout for experts, talent and case studies.','atelier'],['community','Community-led','An events, membership and participation layout.','momentum-events'],['advisory','Advisory-led','A trust-first layout with credibility stats for advisors and consultants.','vault-advisory'],['showcase','Showcase-led','An image-forward layout for a featured listing or property.','crest-realty']] as const;
const styles=[['ocean','Ocean','Clear, calm and trusted'],['midnight','Midnight','Focused, bold and technical'],['ember','Ember','Warm, welcoming and human'],['teal','Teal','Modern, purposeful and balanced']] as const;
const capabilityByLayout:Record<string,string[]>={'service-led':['Service enquiry','CMS pages','Responsive layout'],catalogue:['Catalogue structure','Product/service enquiry','CMS pages'],'story-led':['Impact storytelling','Programme pages','CMS pages'],conversion:['Campaign landing page','Lead capture','Analytics-ready'],portfolio:['Case-study pages','Profile showcase','CMS pages'],community:['Event pages','Community updates','CMS pages'],advisory:['Trust indicators','Consultation booking','CMS pages'],showcase:['Listing showcase','Enquiry capture','CMS pages']};
const siteTemplateById=new Map(SITE_TEMPLATES.map(t=>[t.id,t]));
for(const[layout,,,siteTemplateId]of layouts)if(!siteTemplateById.has(siteTemplateId))throw new Error(`Unknown site template ${siteTemplateId} for layout ${layout}`);
export const templateProfiles:TemplateProfile[]=industries.flatMap(([industry,category,pages],industryIndex)=>layouts.flatMap(([layout,layoutLabel,summary,siteTemplateId],layoutIndex)=>styles.map(([style,styleLabel,styleSummary],styleIndex)=>({id:`TPL-${String(industryIndex+1).padStart(2,'0')}-${String(layoutIndex+1).padStart(2,'0')}-${String(styleIndex+1).padStart(2,'0')}`,name:`${industry} · ${layoutLabel} · ${styleLabel}`,industry,category,layout,layoutLabel,siteTemplateId,siteTemplateName:siteTemplateById.get(siteTemplateId)!.name,heroShape:siteTemplateById.get(siteTemplateId)!.heroShape,style:style as TemplateStyle,styleLabel,summary:`${summary} ${styleSummary}.`,pages:[...pages],capabilities:capabilityByLayout[layout],supportedStacks:['React + FastAPI','Next.js + FastAPI','WordPress','Laravel','Angular','Odoo 18','Odoo 19','Static HTML']}))));
export const templateIndustries=[...new Set(templateProfiles.map(t=>t.industry))];
export const templateLayouts=[...new Set(templateProfiles.map(t=>t.layout))];
export const templateStyles=[...new Set(templateProfiles.map(t=>t.style))];
export const templateById=(id:string)=>templateProfiles.find(t=>t.id===id);
